### ISSUE TITLE
Not sending emails and no errors shown

### ISSUE THREAD

**Issue by ghtmtt** [getgrav/grav-plugin-form#359]
Hi,

after updating grav, plugins and themes the form plugin is not working properly.

I don’t have any forms.html.twig replacing the standard template and I can fill the form with the values.

BUT when clicking on submit nothing happens. By nothing I mean that no email is sent, no “green box” is displayed with the message “thanks for contacting us” but at the same time no errors on the logs.

I'm on a Debian 10 server and apache. Grav version 1.6.11

**Comment by rhukster** [comment]
My hunch is that you have your reset after message.  Try putting message after. 

This is fixed in develop btw.  But changing order is a quick fix.

**Comment by ghtmtt** [comment]
thanks for answering. The final lines of the yaml are:


   ```
 buttons:
        -
            type: submit
            value: Submit
        -
            type: reset
            value: Reset
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to:
                    - '{{ config.plugins.email.to }}'
                    - '{{ form.value.email }}'
                subject: 'Iscrizione {{ form.value.corso }} per {{ form.value.name|e }} {{ form.value.cognome|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: iscrizione-
                filename: iscritti.txt
                dateformat: Ymd-His-u
                operation: add
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            postgres: null
        -
            message: 'Thanks for contacting us'
```

are you suggesting to put `buttons` at the end of the yaml after `message`?

**Comment by well-made** [comment]
Did you find a fix? I think i'm having the same issue here. Mine refreshes the page and leaves all inputs blank.

**Comment by ghtmtt** [comment]
nope. I'm still on the old version of grav because with this bug I cannot update the website.

**Comment by rhukster** [comment]
Is this a modular form page? perhaps the form is not getting processed at all.

**Comment by well-made** [comment]
@rhukster the new version `3.0.8` works :) thanks for the fix

**Comment by mahagr** [comment]
@ghtmtt This issue should be fixed in released version.

**Comment by prismplex** [comment]
Hi,
thank you all for the comments and the fixes. Unfortunately I am still having issues with a modular contact form which worked before these updates. Currently I am using `Form 3.0.9` and `Grav 1.6.16`. When I try to submit the form, the page simply refreshes and the leaves all inputs blank.
My `form.de.md` looks like this
```
---
title: Kontaktformular
form:
    action: /contact
    name: contact-form
    fields:
        -
            name: name
            label: Name
            placeholder: 'Ihr Name'
            autocomplete: 'on'
            type: text
            validate:
                required: true
        -
            name: email
            label: Email
            placeholder: 'Ihre Emailadresse'
            type: email
            validate:
                required: true
        -
            name: message
            label: Nachricht
            placeholder: 'Ihre Nachricht'
            type: textarea
            validate:
                required: true
        -
            name: terms
            label: 'Ich habe die Datenschutzerklärung gelesen, verstanden und akzeptiert.'
            type: checkbox
            validate:
                required: true
    buttons:
        -
            type: submit
            value: Abschicken
        -
            type: reset
            value: Reset
    process:
        -
            email:
                from: '{{ config.plugins.email.from }}'
                to:
                    - '{{ config.plugins.email.to }}'
                    - '{{ form.value.email }}'
                subject: '[Feedback] {{ form.value.name|e }}'
                body: '{% include ''forms/data.html.twig'' %}'
        -
            save:
                fileprefix: feedback-
                dateformat: Ymd-His-u
                extension: txt
                body: '{% include ''forms/data.txt.twig'' %}'
        -
            message: 'Danke für Ihre Nachricht!'
        -
            display: thankyou
---
```
My parent `modular.de.md`:
```
---
title: Kontakt
menu: Kontakt
onpage_menu: false
body_classes: 'modular header-image fullwidth'
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _header
            - _intro
            - _contact
---
```
I am sure I missed some important changes coming with these updates, but unfortunately I do not know where to search...

**Comment by prismplex** [comment]
Yep, you are definitely right, thank you!
I had to blacklist the `/contact` page in the `Grav AdvancedPageCache Plugin`. The previously declared `cache_enable: false` did not work. It seems, that there was a change in the `Grav AdvancedPageCache Plugin`.
Thank you again. Not a form bug.

**Comment by rhukster** [comment]
Ah yes, this would be a problem with AdvancedPageCache plugin.. Blacklisting the form page is the correct solution.
